### Sandbox  

#### Content  
1. Get Dims  
    - StockPoints and Coordinations
    - StockPoints Mapping (State, LGA, LCDA)

#### 1. Get SP Dims

In [31]:
import pandas as pd
import pyodbc  # or sqlalchemy, depending on your setup
from codebase.database.get_connection import get_connection_string, get_connection
from codebase.utils.utils import setup_logging 
import warnings
# from jinja2 import Template

In [32]:
logger = setup_logging(log_dir='log-sandbox-sp-clustering-and-routing', projname='log-sandbox-sp-clustering-and-routing')

In [33]:
# Get Connection
repl_con_string = get_connection_string(logger = logger, database='VconnectMasterDWR', server_type='replica')

In [12]:
# conn.close()

In [40]:
## Stock Point Dim: Stock_Point_ID	Stock_point_Name	Lattitude	Longitude
try:
    with pyodbc.connect(repl_con_string) as conn:
        warnings.simplefilter("ignore", UserWarning) 
        with open("_sql/sp_dim.sql", 'r') as file:
            sql_query = file.read()
        df_sp_dim = pd.read_sql(sql_query, con = conn) 
    
    if not df_sp_dim.empty:
        df_sp_dim.to_feather('./input/df_sp_dim.feather')
except Exception as e:
    logger.error(f'Error fetch stock_point_dim:\n{e}')

In [41]:
## Stock Point Dim: Stock_Point_ID	Stock_point_Name	Lattitude	Longitude
try:
    with pyodbc.connect(repl_con_string) as conn:
        warnings.simplefilter("ignore", UserWarning) 
        with open("_sql/sp_location_map.sql", 'r') as file:
            sql_query = file.read()
        df_sp_location_mapping= pd.read_sql(sql_query, con = conn) 
    
    if not df_sp_location_mapping.empty:
        df_sp_location_mapping.to_feather('./input/df_sp_location_mapping.feather')
except Exception as e:
    logger.error(f'Error fetch stock point location mapping:\n{e}')

In [42]:
df_sp_location_mapping

,FCID,StockPointName,StateName,State_ID,Region,LGA,LGA_ID,LCDA,LCDA_ID
0,1645887,Surulere FC,Lagos,125,None,Self Pick Lagos,5845,Self Pick Surulere,46431
1,1646038,Kaduna FC,Kaduna,119,NC3,Kaduna North,1358,Abakpa Abakpa,65152
2,1646038,Kaduna FC,Kaduna,119,NC3,Kaduna North,1358,Babban Saura Babban Saura,65153
3,1646038,Kaduna FC,Kaduna,119,NC3,Kaduna North,1358,Badiko Badiko,65154
4,1646038,Kaduna FC,Kaduna,119,NC3,Kaduna North,1358,Barden Yana Barden Yana,65155
...,...,...,...,...,...,...,...,...,...
11116,1647442,OmniHub Ikom Cross River - 910 Side Hustle,Cross River,110,SS2,Ikom,1186,Union Bank,9415
11117,1647442,OmniHub Ikom Cross River - 910 Side Hustle,Cross River,110,SS2,Ikom,1186,Uyo Street.,9416
11118,1647442,OmniHub Ikom Cross River - 910 Side Hustle,Cross River,110,SS2,Ikom,1186,W E P C O,9417
11119,1647442,OmniHub Ikom Cross River - 910 Side Hustle,Cross River,110,SS2,Ikom,1186,Water Boaroad,9418
11120,1647442,OmniHub Ikom Cross River - 910 Side Hustle,Cross River,110,SS2,Ikom,1186,Yala Street.,9419